Allow changing the filter's label
rodrigopaco1986/simple-daterange-picker pull request #9
Opened 2024-12-11 15:21 UTC by crispossa

This PR introduces a new option when instantiating the filter, allowing developers to edit the filter's name.

2024-12-11 16:56 UTC, migueliriano requested changes

2024-12-11 16:56 UTC, migueliriano commented on src/Daterangepicker.php
> +        }
This condition can be removed, `public $name = '',` going to uses the value that is passed in the constructor, if not going to be empty.

2024-12-11 17:37 UTC, migueliriano commented
Doing another check, just noticed that the package already supports a `name` using `->withMeta` method.

So, this PR is not needed, example use:

```php
public function filters(Request $request)
{
    return [
        (new Daterangepicker(
            'users.created_at',
        ))->withMeta(['name' => "Filter by Date"])
    ];
}
```

2024-12-11 18:02 UTC, closed without merging

2024-12-19 04:04 UTC, rodrigopaco1986 commented
these next days I'm gonna have some free time to merge PRs and add some improvements (y)